FIND_PATH(VMime_INCLUDE_DIRS vmime/vmime.hpp)

SET(VMime_NAMES ${VMime_NAMES} vmime)
FIND_LIBRARY(VMime_LIBRARIES NAMES ${VMime_NAMES} )

# handle the QUIETLY and REQUIRED arguments and set VMime_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE( FindPackageHandleStandardArgs )
FIND_PACKAGE_HANDLE_STANDARD_ARGS(VMime DEFAULT_MSG VMime_LIBRARIES VMime_INCLUDE_DIRS)

MARK_AS_ADVANCED(VMime_LIBRARIES VMime_INCLUDE_DIRS )
